"apiVersion": "argoproj.io/v1alpha1"
"kind": "Application"
"metadata":
  "name": "argocd"
  "namespace": "argocd"
"spec":
  "destination":
    "namespace": "argocd"
    "server": "https://kubernetes.default.svc"
  "project": "default"
  "source":
    "chart": "argo-cd"
    "helm":
      "parameters":
      - "name": "server.rbacConfig.policy\\.default"
        "value": "role:readonly"
      - "name": "server.rbacConfig.policy\\.csv"
        "value": |
          g, administrators, role:admin
      - "name": "server.config.oidc\\.config"
        "value": |
          "clientID": "3trs65lp2kpqoroucvfv931bce"
          "clientSecret": "KMS_ENC:AQICAHgv73O8d5VxOFuKpIH7FPfSbU5JSgI0oK4TMmwCS8gasQHeOkb7E2wUjZ/HTAByRrk/AAAAlDCBkQYJKoZIhvcNAQcGoIGDMIGAAgEAMHsGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMeNXNV1GmfEqml9DBAgEQgE6xsfdrTqjhwmeum3vz7JDpFfquTEX6x6zgmvs5pgHIK/UezlWqptDJC6nrBzGlE7jzkgrthHyA/rADFEO8uhQv3oM6q+l445IGW7Km4vc=:"
          "issuer": "https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_qPrN5OkOG"
          "name": "Cognito"
          "requestedIDTokenClaims":
            "cognito:groups":
              "essential": true
          "requestedScopes":
          - "openid"
          - "profile"
          - "email"
      - "name": "server.ingress.paths[0]"
        "value": "/*"
      - "name": "server.extraArgs[0]"
        "value": "--insecure"
      - "name": "server.service.type"
        "value": "NodePort"
      - "name": "configs.secret.argocdServerAdminPassword"
        "value": "$2a$10$Ut9jInfknAJ58Kg8SK8jKe9BujC5Kc9VlcT3k6YxcFNu5/mOzeOs2"
      - "name": "server.ingress.enabled"
        "value": "true"
      - "name": "server.config.url"
        "value": "https://argocd.dev-sak-120-116-11.learn-mlops.com"
      - "name": "server.ingress.tls[0].hosts[0]"
        "value": "argocd.dev-sak-120-116-11.learn-mlops.com"
      - "name": "server.ingress.hosts[0]"
        "value": "argocd.dev-sak-120-116-11.learn-mlops.com"
      - "name": "server.ingress.tls[0].secretName"
        "value": "argocd-dev-sak-120-116-11.learn-mlops.com-tls"
      - "name": "server.ingress.annotations.alb\\.ingress\\.kubernetes\\.io/certificate-arn"
        "value": "arn:aws:acm:eu-central-1:863518836478:certificate/9ea373a8-8bf5-4405-b9b2-c8d00deb3e55"
      - "name": "server.ingress.annotations.alb\\.ingress\\.kubernetes\\.io/listen-ports"
        "value": "[{\"HTTPS\":443}]"
      - "name": "server.ingress.annotations.alb\\.ingress\\.kubernetes\\.io/scheme"
        "value": "internet-facing"
      - "name": "server.ingress.annotations.kubernetes\\.io/ingress\\.class"
        "value": "alb"
      - "name": "dex.enabled"
        "value": "false"
      - "name": "global.securityContext.fsGroup"
        "value": "999"
      - "name": "installCRDs"
        "value": "false"
      - "name": "repoServer.env[0].name"
        "value": "AWS_DEFAULT_REGION"
      - "name": "repoServer.env[0].value"
        "value": "eu-central-1"
      - "name": "repoServer.serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
        "value": "arn:aws:iam::863518836478:role/dev-sak-120-116-11_argocd"
      - "name": "repoServer.serviceAccount.create"
        "value": "true"
      - "name": "repoServer.volumeMounts[0].mountPath"
        "value": "/opt/decryptor/bin"
      - "name": "repoServer.volumeMounts[0].name"
        "value": "decryptor"
      - "name": "repoServer.volumes[0].configMap.items[0].key"
        "value": "decryptor"
      - "name": "repoServer.volumes[0].configMap.items[0].path"
        "value": "decryptor"
      - "name": "repoServer.volumes[0].configMap.name"
        "value": "argocd-decryptor"
      - "name": "repoServer.volumes[0].name"
        "value": "decryptor"
      - "name": "server.config.configManagementPlugins"
        "value": |
          - "generate":
              "args":
              - "/opt/decryptor/bin/decryptor"
              "command":
              - "/usr/bin/python3"
            "init":
              "args":
              - "install"
              - "boto3"
              "command":
              - "/usr/bin/pip3"
            "name": "decryptor"
    "repoURL": "https://argoproj.github.io/argo-helm"
    "targetRevision": "2.7.4"
  "syncPolicy":
    "automated":
      "prune": true
      "selfHeal": true
