"apiVersion": "argoproj.io/v1alpha1"
"kind": "Application"
"metadata":
  "name": "cert-manager"
  "namespace": "argocd"
"spec":
  "destination":
    "namespace": "cert-manager"
    "server": "https://kubernetes.default.svc"
  "project": "default"
  "source":
    "chart": "cert-manager"
    "helm":
      "parameters":
      - "name": "installCRDs"
        "value": "true"
      - "name": "rbac.serviceAccountAnnotations.eks\\.amazonaws\\.com/role-arn"
        "value": "arn:aws:iam::863518836478:role/dev-sak-120-116-10_cert-manager"
      - "name": "aws.region"
        "value": "eu-central-1"
      - "name": "domainFilters[0]"
        "value": "dev-sak-120-116-10.learn-mlops.com"
    "repoURL": "https://charts.jetstack.io"
    "targetRevision": "v0.15.1"
  "syncPolicy":
    "automated":
      "prune": true
      "selfHeal": true
