"apiVersion": "argoproj.io/v1alpha1"
"kind": "Application"
"metadata":
  "name": "kubeflow"
  "namespace": "argocd"
"spec":
  "destination":
    "namespace": "kubeflow"
    "server": "https://kubernetes.default.svc"
  "project": "default"
  "source":
    "path": "argocd/applications/kfdefs"
    "repoURL": "https://github.com/karlschriek/kubeflow-argocd"
    "targetRevision": "master"
  "syncPolicy":
    "automated":
      "prune": true
      "selfHeal": true
    "syncOptions":
    - "CreateNamespace=false"
