"apiVersion": "argoproj.io/v1alpha1"
"kind": "Application"
"metadata":
  "name": "mlflow"
  "namespace": "argocd"
"spec":
  "destination":
    "namespace": "mlflow"
    "server": "https://kubernetes.default.svc"
  "project": "default"
  "source":
    "path": "argocd/applications/mlflow-defs"
    "repoURL": "https://github.com/at-gmbh/kubeflow-argocd"
    "targetRevision": "863518836478/dev-kaas-9.learn-mlops.com"
  "syncPolicy":
    "automated":
      "prune": true
      "selfHeal": true
    "syncOptions":
    - "CreateNamespace=false"
