"apiVersion": "cert-manager.io/v1alpha2"
"kind": "ClusterIssuer"
"metadata":
  "name": "letsencrypt-prod"
"spec":
  "acme":
    "email": "karl.schriek@alexanderthamm.com"
    "privateKeySecretRef":
      "name": "letsencrypt-prod"
    "server": "https://acme-v02.api.letsencrypt.org/directory"
    "solvers":
    - "dns01":
        "route53":
          "hostedZoneID": "Z06905412VTC2I89MGQ6L"
          "region": "eu-central-1"
